---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-tnb-bundle
data:
  ARCHIVE_NAME: zcashd-tnb-artifacts-d292376.tgz
  ARCHIVE_HTTP_SRC: https://gateway.pinata.cloud/ipfs/QmemvQmN8bdqH2S7EZQ3hCXsmoGbTXNcN5vaL98CVQ2yXv
  SNAPSHOT_NAME: zcash-testnet-miner-1009419.tgz
  SNAPSHOT_HTTP_SRC: https://gateway.pinata.cloud/ipfs/QmZwuN84PVBKqZQV1kuJSCvYX9L31vh2PJAA2129wdrZ37
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcashd-testnet-miner-config
data:
  ZCASHD_RPCPORT: "38232"
  ZCASHD_RPCUSER: "zcashrpc"
  zcash.conf: |
    listen=1
    testnet=1
    showmetrics=0
    logips=1
    dns=0
    gen=1
    experimentalfeatures=1
    txindex=1
    insightexplorer=0
    printtoconsole=1
    equihashsolver=tromp
    genproclimit=1
    rpcuser=zcashrpc
    rpcport=38232
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-tnb-base
data:
  ZCASHD_NETWORK: "testnet"
  ZCASHD_RPCUSER: "zcashrpc"
  ZCASHD_LOGIPS: "1"
  ZCASHD_EXPERIMENTALFEATURES: "1"
  ZCASHD_TXINDEX: "1"
  ZCASHD_INSIGHTEXPLORER: "1"
  ZCASHD_ZMQPORT: "9904"
  ZCASHD_RPCBIND: "0.0.0.0"
  ZCASHD_RPCPORT: "38232"
  ZCASHD_ALLOWIP: "0.0.0.0/0"
